### ISSUE TITLE
Transaction submitted twice

### ISSUE THREAD

**Issue by bitbeckers** [raid-guild/wrapeth#23]
Based on Whisper in Discord:
 _I'm having an issue with wrapeth where for some reason by transaction to wrap some eth got duplicated and now the second transaction can't go through because there isn't enough ETH remaining in my wallet_

**Comment by TrustwalletAdmin** [comment]
Hello, good day , due to time difference and interval we are not supposed to text you first at this time,but we were worried and concerned about the support you need,and please note..non of our admins will ask you for your private key, kindly beware of scammers,By the way ;has anyone been able to answer and solve the complaint for you among our admins?
